In [5]:
import torch
import torch.autograd as autograd
import torch.nn as nn
import torch.optim as optim

In [10]:
torch.FloatTensor([[0.5, 0.1], [0.2, 0.11]]) == torch.tensor([[0.5, 0.1], [0.2, 0.11]])

tensor([[True, True],
        [True, True]])

In [15]:
torch.LongTensor([[0.5, 0.1], [0.2, 0.11]], requires_grad=True)

TypeError: new() received an invalid combination of arguments - got (list, requires_grad=bool), but expected one of:
 * (*, torch.device device)
      didn't match because some of the keywords were incorrect: requires_grad
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, *, torch.device device)
 * (object data, *, torch.device device)


In [21]:
torch.FloatTensor([[1,2,3], [4,5,6]]).mean(axis=0).shape

torch.Size([3])

In [30]:
a = nn.ReLU

In [31]:
nn.Sequential(a())

Sequential(
  (0): ReLU()
)

In [33]:
a = nn.ReLU()
nn.Sequential(a)

Sequential(
  (0): ReLU()
)

In [34]:
for i in range(10):
    pass

In [35]:
print(i)

9


In [43]:
from typing import OrderedDict


OrderedDict

typing.OrderedDict

In [18]:
nn.Sequential(*[nn.Linear(200, 200), nn.ReLU()]).comp

Parameter containing:
tensor([[ 0.0070,  0.0557,  0.0525,  ..., -0.0601,  0.0608,  0.0517],
        [ 0.0677,  0.0466, -0.0083,  ..., -0.0292, -0.0627,  0.0033],
        [ 0.0348, -0.0327, -0.0379,  ..., -0.0530, -0.0328, -0.0608],
        ...,
        [ 0.0253,  0.0594, -0.0040,  ...,  0.0212, -0.0238, -0.0108],
        [ 0.0085,  0.0543,  0.0204,  ..., -0.0666,  0.0050,  0.0202],
        [ 0.0560, -0.0690,  0.0644,  ..., -0.0140,  0.0688,  0.0706]],
       requires_grad=True)
Parameter containing:
tensor([ 0.0271,  0.0216, -0.0364, -0.0056,  0.0692, -0.0616,  0.0180, -0.0332,
        -0.0147, -0.0078,  0.0689, -0.0285, -0.0080,  0.0300,  0.0677, -0.0087,
         0.0383, -0.0130,  0.0073,  0.0057, -0.0082,  0.0503,  0.0597,  0.0163,
        -0.0350, -0.0166,  0.0551, -0.0243,  0.0588, -0.0212, -0.0696, -0.0583,
        -0.0029, -0.0483,  0.0268,  0.0670, -0.0083,  0.0083,  0.0175,  0.0582,
        -0.0305,  0.0358,  0.0696,  0.0339,  0.0688,  0.0073, -0.0521, -0.0398,
        -0.0489

In [3]:
def load_config(path):
    import yaml
    return yaml.load(open(path, 'r'), Loader=yaml.SafeLoader)

load_config("../config.yaml")

{'layer_specs': [200, 200],
 'activation': 'ReLU',
 'penalty': 'Otherwise',
 'optimizer': 'SGD',
 'nesterov': True,
 'momentum': 0.9,
 'lr_decay': 0.5,
 'dropout_proportion': 0.1}

In [14]:
torch.FloatTensor([[[0.5, 0.1], [0.2, 0.11]], [[0.5, 0/2], [0.22, 0.74]]]).view(-1)

tensor([0.5000, 0.1000, 0.2000, 0.1100, 0.5000, 0.0000, 0.2200, 0.7400])